---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-galera
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  MYSQL_USER:  {{ .Values.mysql.user.name | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.user.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootpw | b64enc | quote }}
